# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_computation_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61sync_computation_service.proto\"\"\n\nAddRequest\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\x0bSortRequest\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"$\n\x0cSortResponse\x12\x14\n\x0csorted_array\x18\x01 \x03(\x05\")\n\x11OperationResponse\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\"$\n\x0c\x46\x65tchRequest\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\"i\n\rFetchResponse\x12$\n\x0c\x61\x64\x64_response\x18\x01 \x01(\x0b\x32\x0c.AddResponseH\x00\x12&\n\rsort_response\x18\x02 \x01(\x0b\x32\r.SortResponseH\x00\x42\n\n\x08response2\xe5\x01\n\x12\x43omputationService\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12#\n\x04Sort\x12\x0c.SortRequest\x1a\r.SortResponse\x12+\n\x08\x41syncAdd\x12\x0b.AddRequest\x1a\x12.OperationResponse\x12-\n\tAsyncSort\x12\x0c.SortRequest\x1a\x12.OperationResponse\x12,\n\x0b\x46\x65tchResult\x12\r.FetchRequest\x1a\x0e.FetchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'async_computation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=35
  _globals['_ADDREQUEST']._serialized_end=69
  _globals['_ADDRESPONSE']._serialized_start=71
  _globals['_ADDRESPONSE']._serialized_end=100
  _globals['_SORTREQUEST']._serialized_start=102
  _globals['_SORTREQUEST']._serialized_end=130
  _globals['_SORTRESPONSE']._serialized_start=132
  _globals['_SORTRESPONSE']._serialized_end=168
  _globals['_OPERATIONRESPONSE']._serialized_start=170
  _globals['_OPERATIONRESPONSE']._serialized_end=211
  _globals['_FETCHREQUEST']._serialized_start=213
  _globals['_FETCHREQUEST']._serialized_end=249
  _globals['_FETCHRESPONSE']._serialized_start=251
  _globals['_FETCHRESPONSE']._serialized_end=356
  _globals['_COMPUTATIONSERVICE']._serialized_start=359
  _globals['_COMPUTATIONSERVICE']._serialized_end=588
# @@protoc_insertion_point(module_scope)
