# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comp_service_pb2 as comp__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comp_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ComputationStub(object):
    """The computation service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/computation.Computation/Add',
                request_serializer=comp__service__pb2.AddRequest.SerializeToString,
                response_deserializer=comp__service__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Sort = channel.unary_unary(
                '/computation.Computation/Sort',
                request_serializer=comp__service__pb2.SortRequest.SerializeToString,
                response_deserializer=comp__service__pb2.SortResponse.FromString,
                _registered_method=True)
        self.AddAsync = channel.unary_unary(
                '/computation.Computation/AddAsync',
                request_serializer=comp__service__pb2.AddRequest.SerializeToString,
                response_deserializer=comp__service__pb2.AckResponse.FromString,
                _registered_method=True)
        self.SortAsync = channel.unary_unary(
                '/computation.Computation/SortAsync',
                request_serializer=comp__service__pb2.SortRequest.SerializeToString,
                response_deserializer=comp__service__pb2.AckResponse.FromString,
                _registered_method=True)
        self.GetAddResult = channel.unary_unary(
                '/computation.Computation/GetAddResult',
                request_serializer=comp__service__pb2.ResultRequest.SerializeToString,
                response_deserializer=comp__service__pb2.AddResponse.FromString,
                _registered_method=True)
        self.GetSortResult = channel.unary_unary(
                '/computation.Computation/GetSortResult',
                request_serializer=comp__service__pb2.ResultRequest.SerializeToString,
                response_deserializer=comp__service__pb2.SortResponse.FromString,
                _registered_method=True)


class ComputationServicer(object):
    """The computation service definition.
    """

    def Add(self, request, context):
        """Synchronous RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAsync(self, request, context):
        """Asynchronous RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SortAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSortResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=comp__service__pb2.AddRequest.FromString,
                    response_serializer=comp__service__pb2.AddResponse.SerializeToString,
            ),
            'Sort': grpc.unary_unary_rpc_method_handler(
                    servicer.Sort,
                    request_deserializer=comp__service__pb2.SortRequest.FromString,
                    response_serializer=comp__service__pb2.SortResponse.SerializeToString,
            ),
            'AddAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAsync,
                    request_deserializer=comp__service__pb2.AddRequest.FromString,
                    response_serializer=comp__service__pb2.AckResponse.SerializeToString,
            ),
            'SortAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.SortAsync,
                    request_deserializer=comp__service__pb2.SortRequest.FromString,
                    response_serializer=comp__service__pb2.AckResponse.SerializeToString,
            ),
            'GetAddResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddResult,
                    request_deserializer=comp__service__pb2.ResultRequest.FromString,
                    response_serializer=comp__service__pb2.AddResponse.SerializeToString,
            ),
            'GetSortResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSortResult,
                    request_deserializer=comp__service__pb2.ResultRequest.FromString,
                    response_serializer=comp__service__pb2.SortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computation.Computation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computation.Computation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Computation(object):
    """The computation service definition.
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Add',
            comp__service__pb2.AddRequest.SerializeToString,
            comp__service__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Sort',
            comp__service__pb2.SortRequest.SerializeToString,
            comp__service__pb2.SortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/AddAsync',
            comp__service__pb2.AddRequest.SerializeToString,
            comp__service__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SortAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/SortAsync',
            comp__service__pb2.SortRequest.SerializeToString,
            comp__service__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/GetAddResult',
            comp__service__pb2.ResultRequest.SerializeToString,
            comp__service__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSortResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/GetSortResult',
            comp__service__pb2.ResultRequest.SerializeToString,
            comp__service__pb2.SortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
