# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import computation_pb2 as computation__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ComputationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Addition = channel.unary_unary(
                '/computation.Computation/Addition',
                request_serializer=computation__pb2.AdditionRequest.SerializeToString,
                response_deserializer=computation__pb2.AdditionResponse.FromString,
                _registered_method=True)
        self.Sorting = channel.unary_unary(
                '/computation.Computation/Sorting',
                request_serializer=computation__pb2.SortingRequest.SerializeToString,
                response_deserializer=computation__pb2.SortingResponse.FromString,
                _registered_method=True)
        self.AsyncAddition = channel.unary_unary(
                '/computation.Computation/AsyncAddition',
                request_serializer=computation__pb2.AdditionRequest.SerializeToString,
                response_deserializer=computation__pb2.AsyncTaskResponse.FromString,
                _registered_method=True)
        self.AsyncSorting = channel.unary_unary(
                '/computation.Computation/AsyncSorting',
                request_serializer=computation__pb2.SortingRequest.SerializeToString,
                response_deserializer=computation__pb2.AsyncTaskResponse.FromString,
                _registered_method=True)
        self.RetrieveResult = channel.unary_unary(
                '/computation.Computation/RetrieveResult',
                request_serializer=computation__pb2.ResultQuery.SerializeToString,
                response_deserializer=computation__pb2.ResultQueryResponse.FromString,
                _registered_method=True)


class ComputationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Addition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sorting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncAddition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncSorting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Addition': grpc.unary_unary_rpc_method_handler(
                    servicer.Addition,
                    request_deserializer=computation__pb2.AdditionRequest.FromString,
                    response_serializer=computation__pb2.AdditionResponse.SerializeToString,
            ),
            'Sorting': grpc.unary_unary_rpc_method_handler(
                    servicer.Sorting,
                    request_deserializer=computation__pb2.SortingRequest.FromString,
                    response_serializer=computation__pb2.SortingResponse.SerializeToString,
            ),
            'AsyncAddition': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncAddition,
                    request_deserializer=computation__pb2.AdditionRequest.FromString,
                    response_serializer=computation__pb2.AsyncTaskResponse.SerializeToString,
            ),
            'AsyncSorting': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncSorting,
                    request_deserializer=computation__pb2.SortingRequest.FromString,
                    response_serializer=computation__pb2.AsyncTaskResponse.SerializeToString,
            ),
            'RetrieveResult': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveResult,
                    request_deserializer=computation__pb2.ResultQuery.FromString,
                    response_serializer=computation__pb2.ResultQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computation.Computation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computation.Computation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Computation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Addition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Addition',
            computation__pb2.AdditionRequest.SerializeToString,
            computation__pb2.AdditionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sorting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Sorting',
            computation__pb2.SortingRequest.SerializeToString,
            computation__pb2.SortingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncAddition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/AsyncAddition',
            computation__pb2.AdditionRequest.SerializeToString,
            computation__pb2.AsyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncSorting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/AsyncSorting',
            computation__pb2.SortingRequest.SerializeToString,
            computation__pb2.AsyncTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/RetrieveResult',
            computation__pb2.ResultQuery.SerializeToString,
            computation__pb2.ResultQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
