# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computation_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63omputation_service.proto\"\"\n\nAddRequest\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\x0bSortRequest\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"$\n\x0cSortResponse\x12\x14\n\x0csorted_array\x18\x01 \x03(\x05\x32[\n\x12\x43omputationService\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12#\n\x04Sort\x12\x0c.SortRequest\x1a\r.SortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=29
  _globals['_ADDREQUEST']._serialized_end=63
  _globals['_ADDRESPONSE']._serialized_start=65
  _globals['_ADDRESPONSE']._serialized_end=94
  _globals['_SORTREQUEST']._serialized_start=96
  _globals['_SORTREQUEST']._serialized_end=124
  _globals['_SORTRESPONSE']._serialized_start=126
  _globals['_SORTRESPONSE']._serialized_end=162
  _globals['_COMPUTATIONSERVICE']._serialized_start=164
  _globals['_COMPUTATIONSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
