# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63omputation.proto\x12\x0b\x63omputation\"-\n\x0f\x41\x64\x64itionRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1f\n\x10\x41\x64\x64itionResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"!\n\x0eSortingRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\")\n\x0fSortingResponse\x12\x16\n\x0esorted_numbers\x18\x01 \x03(\x05\"4\n\x11\x41syncTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\"\x1e\n\x0bResultQuery\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"r\n\x13ResultQueryResponse\x12\x19\n\x0f\x61\x64\x64ition_result\x18\x01 \x01(\x05H\x00\x12\x36\n\x0esorting_result\x18\x02 \x01(\x0b\x32\x1c.computation.SortingResponseH\x00\x42\x08\n\x06result2\x86\x03\n\x0b\x43omputation\x12G\n\x08\x41\x64\x64ition\x12\x1c.computation.AdditionRequest\x1a\x1d.computation.AdditionResponse\x12\x44\n\x07Sorting\x12\x1b.computation.SortingRequest\x1a\x1c.computation.SortingResponse\x12M\n\rAsyncAddition\x12\x1c.computation.AdditionRequest\x1a\x1e.computation.AsyncTaskResponse\x12K\n\x0c\x41syncSorting\x12\x1b.computation.SortingRequest\x1a\x1e.computation.AsyncTaskResponse\x12L\n\x0eRetrieveResult\x12\x18.computation.ResultQuery\x1a .computation.ResultQueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDITIONREQUEST']._serialized_start=34
  _globals['_ADDITIONREQUEST']._serialized_end=79
  _globals['_ADDITIONRESPONSE']._serialized_start=81
  _globals['_ADDITIONRESPONSE']._serialized_end=112
  _globals['_SORTINGREQUEST']._serialized_start=114
  _globals['_SORTINGREQUEST']._serialized_end=147
  _globals['_SORTINGRESPONSE']._serialized_start=149
  _globals['_SORTINGRESPONSE']._serialized_end=190
  _globals['_ASYNCTASKRESPONSE']._serialized_start=192
  _globals['_ASYNCTASKRESPONSE']._serialized_end=244
  _globals['_RESULTQUERY']._serialized_start=246
  _globals['_RESULTQUERY']._serialized_end=276
  _globals['_RESULTQUERYRESPONSE']._serialized_start=278
  _globals['_RESULTQUERYRESPONSE']._serialized_end=392
  _globals['_COMPUTATION']._serialized_start=395
  _globals['_COMPUTATION']._serialized_end=785
# @@protoc_insertion_point(module_scope)
