# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompute.proto\x12\x0b\x63omputation\"\"\n\nAddRequest\x12\t\n\x01i\x18\x01 \x01(\x05\x12\t\n\x01j\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\x0bSortRequest\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"$\n\x0cSortResponse\x12\x14\n\x0csorted_array\x18\x01 \x03(\x05\"1\n\rAsyncResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\" \n\rResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"d\n\x0eResultResponse\x12\x14\n\nadd_result\x18\x01 \x01(\x05H\x00\x12\x32\n\rsort_response\x18\x02 \x01(\x0b\x32\x19.computation.SortResponseH\x00\x42\x08\n\x06result2\xce\x02\n\x0b\x43omputation\x12\x38\n\x03\x41\x64\x64\x12\x17.computation.AddRequest\x1a\x18.computation.AddResponse\x12;\n\x04Sort\x12\x18.computation.SortRequest\x1a\x19.computation.SortResponse\x12?\n\x08\x41syncAdd\x12\x17.computation.AddRequest\x1a\x1a.computation.AsyncResponse\x12\x41\n\tAsyncSort\x12\x18.computation.SortRequest\x1a\x1a.computation.AsyncResponse\x12\x44\n\tGetResult\x12\x1a.computation.ResultRequest\x1a\x1b.computation.ResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=30
  _globals['_ADDREQUEST']._serialized_end=64
  _globals['_ADDRESPONSE']._serialized_start=66
  _globals['_ADDRESPONSE']._serialized_end=95
  _globals['_SORTREQUEST']._serialized_start=97
  _globals['_SORTREQUEST']._serialized_end=125
  _globals['_SORTRESPONSE']._serialized_start=127
  _globals['_SORTRESPONSE']._serialized_end=163
  _globals['_ASYNCRESPONSE']._serialized_start=165
  _globals['_ASYNCRESPONSE']._serialized_end=214
  _globals['_RESULTREQUEST']._serialized_start=216
  _globals['_RESULTREQUEST']._serialized_end=248
  _globals['_RESULTRESPONSE']._serialized_start=250
  _globals['_RESULTRESPONSE']._serialized_end=350
  _globals['_COMPUTATION']._serialized_start=353
  _globals['_COMPUTATION']._serialized_end=687
# @@protoc_insertion_point(module_scope)
