# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import compute_pb2 as compute__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in compute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ComputationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/computation.Computation/Add',
                request_serializer=compute__pb2.AddRequest.SerializeToString,
                response_deserializer=compute__pb2.AddResponse.FromString,
                _registered_method=True)
        self.Sort = channel.unary_unary(
                '/computation.Computation/Sort',
                request_serializer=compute__pb2.SortRequest.SerializeToString,
                response_deserializer=compute__pb2.SortResponse.FromString,
                _registered_method=True)
        self.AsyncAdd = channel.unary_unary(
                '/computation.Computation/AsyncAdd',
                request_serializer=compute__pb2.AddRequest.SerializeToString,
                response_deserializer=compute__pb2.AsyncResponse.FromString,
                _registered_method=True)
        self.AsyncSort = channel.unary_unary(
                '/computation.Computation/AsyncSort',
                request_serializer=compute__pb2.SortRequest.SerializeToString,
                response_deserializer=compute__pb2.AsyncResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/computation.Computation/GetResult',
                request_serializer=compute__pb2.ResultRequest.SerializeToString,
                response_deserializer=compute__pb2.ResultResponse.FromString,
                _registered_method=True)


class ComputationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncSort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=compute__pb2.AddRequest.FromString,
                    response_serializer=compute__pb2.AddResponse.SerializeToString,
            ),
            'Sort': grpc.unary_unary_rpc_method_handler(
                    servicer.Sort,
                    request_deserializer=compute__pb2.SortRequest.FromString,
                    response_serializer=compute__pb2.SortResponse.SerializeToString,
            ),
            'AsyncAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncAdd,
                    request_deserializer=compute__pb2.AddRequest.FromString,
                    response_serializer=compute__pb2.AsyncResponse.SerializeToString,
            ),
            'AsyncSort': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncSort,
                    request_deserializer=compute__pb2.SortRequest.FromString,
                    response_serializer=compute__pb2.AsyncResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=compute__pb2.ResultRequest.FromString,
                    response_serializer=compute__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computation.Computation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('computation.Computation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Computation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Add',
            compute__pb2.AddRequest.SerializeToString,
            compute__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/Sort',
            compute__pb2.SortRequest.SerializeToString,
            compute__pb2.SortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/AsyncAdd',
            compute__pb2.AddRequest.SerializeToString,
            compute__pb2.AsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncSort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/AsyncSort',
            compute__pb2.SortRequest.SerializeToString,
            compute__pb2.AsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/computation.Computation/GetResult',
            compute__pb2.ResultRequest.SerializeToString,
            compute__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
