# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comp_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omp_service.proto\x12\x0b\x63omputation\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1c\n\x0bSortRequest\x12\r\n\x05\x61rray\x18\x01 \x03(\x05\"$\n\x0cSortResponse\x12\x14\n\x0csorted_array\x18\x01 \x03(\x05\"\x1e\n\x0b\x41\x63kResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t2\x92\x03\n\x0b\x43omputation\x12\x38\n\x03\x41\x64\x64\x12\x17.computation.AddRequest\x1a\x18.computation.AddResponse\x12;\n\x04Sort\x12\x18.computation.SortRequest\x1a\x19.computation.SortResponse\x12=\n\x08\x41\x64\x64\x41sync\x12\x17.computation.AddRequest\x1a\x18.computation.AckResponse\x12?\n\tSortAsync\x12\x18.computation.SortRequest\x1a\x18.computation.AckResponse\x12\x44\n\x0cGetAddResult\x12\x1a.computation.ResultRequest\x1a\x18.computation.AddResponse\x12\x46\n\rGetSortResult\x12\x1a.computation.ResultRequest\x1a\x19.computation.SortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comp_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=35
  _globals['_ADDREQUEST']._serialized_end=69
  _globals['_ADDRESPONSE']._serialized_start=71
  _globals['_ADDRESPONSE']._serialized_end=100
  _globals['_SORTREQUEST']._serialized_start=102
  _globals['_SORTREQUEST']._serialized_end=130
  _globals['_SORTRESPONSE']._serialized_start=132
  _globals['_SORTRESPONSE']._serialized_end=168
  _globals['_ACKRESPONSE']._serialized_start=170
  _globals['_ACKRESPONSE']._serialized_end=200
  _globals['_RESULTREQUEST']._serialized_start=202
  _globals['_RESULTREQUEST']._serialized_end=234
  _globals['_COMPUTATION']._serialized_start=237
  _globals['_COMPUTATION']._serialized_end=639
# @@protoc_insertion_point(module_scope)
